### ISSUE TITLE
Line numbers in the error messages are incorrectly displayed

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#151]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Jan 25, 2017 at 09:17 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1027_

----

There is a mismatch between the line number that is displayed in the error message and the source view. 
![linenumbererror](https://cloud.githubusercontent.com/assets/1845370/22284345/e2324fbe-e30c-11e6-993d-e0d7759ed797.png)
![linenumbers](https://cloud.githubusercontent.com/assets/1845370/22284347/e5cbe11c-e30c-11e6-97e8-de212dbf71f9.png)

The line number in the error message matches with the code if I open the .bal file in a command prompt. 
![code](https://cloud.githubusercontent.com/assets/1845370/22284388/19c32df4-e30d-11e6-8efe-a3ce24104a76.png)

**Comment by hevayo** [comment]
Based on the provided screens what is saved in the file system differ from what is displayed in the source view this can be a cause of applying formatting to the loaded source without preserving white-space of the source. 

I will close this issue since we preserve white spaces in source now. Please reopen if you encounter this again.
