### ISSUE TITLE
Composer does not render after opening the ballerina service file

### ISSUE THREAD

**Issue by mefarazath** [ballerinalang/composer#1667]
Started up the composer and open my .bal [file](https://gist.github.com/mefarazath/6a05db5611b0ff7fcc20ae48774b4a7b)  from the composer. I created this service using the ballerina intellij plugin (which I think doesn't matter). I can start the service using "Run" --> "Service"

But,
1. The composer does not render the service properly. 
![image](https://cloud.githubusercontent.com/assets/5237653/26222699/a400f3a0-3c38-11e7-99f6-f02a7b542863.png)

Only part of the service is rendered. I cannot scroll down to view the rest of my service.

2. Cannot switch to the source view

Backend prints the below error
`2017-05-19 02:06:04,130 ERROR -  File not found [/home/farazath/Desktop/IML/ballerina/ballerina-tools-0.86/resources/composer/web/undefined], Requesting path [/undefined] `

**Comment by kaviththiranga** [comment]
@mefarazath, while testing your bal file with the latest composer build, I could see an error related to add expression handling in composer - causing a NPE in back-end.  I have fixed the issue with https://github.com/ballerinalang/ballerina/pull/2409. After the fix, I could open the bal file you have attached to the issue without any problems. This fix will be available with next release. 
On a side note, the error message which you have mentioned above is not related to this. It's a known error log while parsing unsaved files on composer and will be fixed in coming releases. 
I am closing the ticket as per the above fix and clarification. Please feel free to reopen if the issue resides further. 
Thanks
