### ISSUE TITLE
Giving a package name with a full-stop character generates syntaxtually incorrect code 

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#1954]
Giving a package name that contains a full-stop character generates incorrect code segment. For example giving test.com produces, 

`packagetest.com;import ballerina.net.http;`

and returns the following response from the validation endpoint,

'{"errors":[{"row":1,"column":11,"text":"<unknown>:1:11: unwanted token '.'","type":"error"},{"row":1,"column":17,"text":"<unknown>:1:17: unwanted token 'import'","type":"error"},{"row":1,"column":33,"text":"<unknown>:1:33: unwanted token '.'","type":"error"},{"row":1,"column":37,"text":"<unknown>:1:37: mismatched input '.'. Expecting one of ';'","type":"error"},{"row":1,"column":42,"text":"<unknown>:1:42: mismatched input ';'. Expecting one of {'[', Identifier}","type":"error"},{"row":3,"column":0,"text":"<unknown>:3:0: unwanted token '@'","type":"error"},{"row":3,"column":5,"text":"<unknown>:3:5: mismatched input ':'. Expecting one of ';'","type":"error"},{"row":3,"column":15,"text":"<unknown>:3:15: unwanted token '{'","type":"error"},{"row":3,"column":21,"text":"<unknown>:3:21: mismatched input ':'. Expecting one of ';'","type":"error"}]}'

**Comment by kaviththiranga** [comment]
This is due to a bug in package definition source gen and is fixed in 
 https://github.com/ballerinalang/composer/pull/1986.
However, as I could have identified, this was not  only related '.' char in package name. To any package name, it will happen if you go in this path.

Open or create a file without a package name. Go to source view, do any modification and come back. Now add a package and go to source view.
