### ISSUE TITLE
Composer return Error in Windows

### ISSUE THREAD

**Issue by chethanadj** [ballerinalang/composer#2119]
Composer does not success to load samples 

In the cmd promt it shows below log
D:\ballerina-tools-0.87\samples\echoService>composer
2017-06-24 14:16:29,760 INFO  - Ballerina Composer URL: http://localhost:9091
2017-06-24 14:16:42,083 ERROR -  File not found [D:\ballerina-tools-0.87\bin\..\
resources\composer\web/undefined], Requesting path [/undefined]

**Comment by hevayo** [comment]
Please try ti run the composer directly from the bin directory. ie.
D:\ballerina-tools-0.87\bin>composer

**Comment by hevayo** [comment]
Printing of the undefined error was a known issue with composer 0.87 version and got fixed in 0.88.

2017-06-24 14:16:42,083 ERROR - File not found [D:\ballerina-tools-0.87\bin..
resources\composer\web/undefined], Requesting path [/undefined]

Can you please try the sample with our latest release 0.88.

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced in the latest master 0.95, hence closing this issue
