### ISSUE TITLE
composer file browser always opens with the root in the machine. Can we switch to the user directory

### ISSUE THREAD

**Issue by nuwanbando** [ballerinalang/composer#2260]
Lets no list all files from root, when trying file open or save with composer.

if we store the first bal file in some location the second file I try to save has to take the previos location by default.

Improve basic file system browser for open / save fuctions

**Comment by NatashaWso2** [comment]
This is fixed in the latest master.

- The user directory is shown when trying to open or save a file in the file-dialog as below : 
![root directory](https://user-images.githubusercontent.com/13446645/32797347-7d2455c8-c997-11e7-9d68-1ee71f0a8b57.png)

- The location of the first bal file saved (previous location of the bal file saved) will be taken by default when saving the the second file as below: 
![samelocation](https://user-images.githubusercontent.com/13446645/32797448-cc7c0be8-c997-11e7-934c-cdc4c6db5b01.png)

Browser for open and save functions is improved in the master, hence this issue can be closed
