### ISSUE TITLE
Cannot write Fork/Join Condition as "some 1 worker1, worker2"

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2301]
The fields will get stuck as shown in the image
![edit](https://user-images.githubusercontent.com/1845370/27945959-01fa8b56-630d-11e7-8642-b39c0cf93d0b.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master. 
Now you can give the join condition as follows : _'some 1 worker1, worker2_' and the design view will not get stuck.
![fork-join](https://user-images.githubusercontent.com/13446645/32796761-badfa4aa-c995-11e7-87b0-d3a039e6708a.png)

Since the fork-join conditions can be provided without any issues, closing this issue.
