### ISSUE TITLE
[ContentAssistance] No suggestions for variables for the condition statement of the loops

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2399]
Pack - tools (14/7)
No suggestions for variables for the condition statement of the loops in the design view

eg: 
if (condition){
}

**Comment by sumuditha-viraj** [comment]
This issue is there when we try to hit ctrl+space inside the brackets of if statement. 

for an example see below example: 

function myFunc (){
    int i = 10;
    int length = 20;
    if (i < length) {
    }
}

If u try to continue typing "i < length" expression inside the brackets it will work as expected. ie. It will suggest "i" and "length" symbols.

Anyhow we need to fix this by improving the parser.

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
