### ISSUE TITLE
[Editor] Samples are opened as Untitled files

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#267]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Feb 03, 2017 at 08:56 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1333_

----

1. Go to the welcome page
2. Open a sample

Issue
The sample is opened as "*untitled". Ideally it should be saved with the correct sample name

**Comment by sumuditha-viraj** [comment]
Current convention of the Composer is to create new files with the name of 'untitled'. It will change the name when user saves the file in the provided file system path with the provided name. 

When you open a sample what it does is it gets the sample ballerina program content and creates a new file. At this stage user hasn't saved the created file, hence we are not giving any name to the file. Actually what we are doing by clicking on a sample is we create a new file with a template content in it(echoService, helloWorld content etc.). User can save that file with any arbitrary name in any file path. 

So that, we will stick to the current convention.
