### ISSUE TITLE
Worker invocation cannot be done from the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2684]
Release 0.91

**Steps**
1. Add an assignment in the default worker/thread
2. Add a worker
3. Call the worker 
eg: a -> worker1

**Issue**
Writing a->worker1 or b<-default is not supported from the design view of the composer

**Comment by nadeeshaan** [comment]
This is not a Blocker. 
According to the current design, we need to have a worker receive statement at the receiving worker, from a particular worker. There is one limitation where we need to type the receiving worker name. After that you can draw the worker invocation from one to the other. This design will be changed in due course. Hence closing the issue.

Note: It is mandatory to have a worker receive statement in order to draw the arrow form sender.
