### ISSUE TITLE
Shouldn't be able to delete all catches.

### ISSUE THREAD

**Issue by manuranga** [ballerinalang/composer#2925]
in try-catch statement, there should be a catch/finally at the end.

**Comment by dilinisg** [comment]
Ideal implementation would be to indicate the user that it is not syntactically correct to delete the catch block when there are no other catch blocks or finally block. This fix is only partially correct because the catch block should be able to delete when there is a finally block. With the fix, this cannot be achieved. Hence, reopening

**Comment by NipunaMarcus** [comment]
This is working as expected in current master. we won't allow user to delete any catch or finally block when following patterns are matched.

```ballerina
try{
}catch(error err){
}
```
or

```ballerina
try{
}finally{
}
```
hence closing this issue.
