### ISSUE TITLE
Overlapping debug button and hamburger icon

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2930]
Release 0.93

![overlap1](https://user-images.githubusercontent.com/1845370/29757712-7f02da22-8bcb-11e7-996f-4bab67d4cc4d.png)

**Comment by dilinisg** [comment]
- In the compact view debug points appear on the side and in other two views in the bottom. So, it is inconsistent.
- In the below image the debug points for the condition and statement appear at the same level, so that it is difficult to identity which one is which

![debugpointlevels](https://user-images.githubusercontent.com/1845370/30321730-acf2cb9e-97d4-11e7-8a8c-c6f39eebe0e0.png)

**Comment by dilinisg** [comment]
Overlapping views in the compact view for transform

![ov1](https://user-images.githubusercontent.com/1845370/30368439-bc0aaa10-988e-11e7-816f-b4f1ccec39c4.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed.

- Action menu without overlapping
![actionmenu](https://user-images.githubusercontent.com/13446645/32599154-aba73cc4-c561-11e7-8ba6-04321e195006.png)

-  In all 3 views the debug points are positioned in the right side

**_Default View_**

![defaultview](https://user-images.githubusercontent.com/13446645/32599275-0dde4dd8-c562-11e7-90b7-4c137828e6b8.png)

_**Action View**_

![actionview](https://user-images.githubusercontent.com/13446645/32599282-16d6e6ca-c562-11e7-87c4-cd32b2a7d4cb.png)

**_Compact View_**

![compactview](https://user-images.githubusercontent.com/13446645/32599297-2185d982-c562-11e7-8f7a-86c8ada1e1dd.png)
