### ISSUE TITLE
Wrong action invocation syntax leading to errors

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3007]
Pack - 04/09

Drag and drop an action.

**Issue**
Wrong action invocation syntax leading to errors:
message m1 = clientConnector.get();

```
resource Resource1 (message m) {
        http:ClientConnector endpoint1 = create http:ClientConnector ();
        message m1 = clientConnector.get();
        reply m;
    }
```

**Comment by nadeeshaan** [comment]
@dilinisg, if you are pointing out the wrong connector instance name, yes that is how it is designed at the moment. After dragging a connector you need to draw the arrow to the desired connector.

**Comment by nadeeshaan** [comment]
This is due to the action invocation drag and drop life cycle. This life cycle has been changed as follows.
If you drag an action invocation we will connect to the most recent and relevant connector invocation and change the syntax accordingly. If there is no connector declaration we create a new one and complete the invocation syntax accordingly.

Hence closing the issue
