### ISSUE TITLE
Identifier literals in the function name is not supported

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3100]
Pack - 0.93 (19/09)

Identifier literals in the function name is not supported. Cannot switch to the design view after the following code segment is added
```
function |combine names| (string |first name|, string |last name|) (string) {
    return |first name| + " " + |last name|;
}
```

**Comment by NatashaWso2** [comment]
Identifier literals in the function name is supported and you can navigate back and forth from source view and the design view without any issue.

![identifier-literals](https://user-images.githubusercontent.com/13446645/33109540-25edec5c-cf68-11e7-878a-199c48c5ad2a.png)

Since this is allowed in the latest master, this issue can be closed.
