### ISSUE TITLE
Assignment statement in design view get reset when a soap client connector is declared

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3416]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

Steps
1. Drop in an assignment statement box to design view
2. Paste the following code snippet inside the box
```soap:ClientConnector soapConnector = create soap:ClientConnector("") ``` [1] 

**Actual behaviour**
The assignment box get reset.

**Expected behaviour**
The code snippet should remain, if the syntax is not valid,  then some way should be there to indicate the syntax error.

[1] https://github.com/ballerinalang/connectors/blob/master/soap/samples/soap/samples.bal

**Comment by NatashaWso2** [comment]
Assignment statement in design view does not get reset when a soap client connector is declared in the latest master.  If the syntax is not valid, then the syntax error is shown both in the source and design view.
![soap-connectore](https://user-images.githubusercontent.com/13446645/33160089-72c4d7e8-d03f-11e7-9a32-4c372af793ec.png)

Since this issue is resolved, this can be closed.
