### ISSUE TITLE
Provide information in creating a client connector instance

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3442]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

How do I create a client connector using composer? What do i need to drag and drop in order to do that?
Could you please provide information on that?

**Comment by NatashaWso2** [comment]
The user can create a client connector by dragging and dropping the client connector construct from the tool palette. 

![clientconnector](https://user-images.githubusercontent.com/13446645/33200427-8f57e964-d11a-11e7-8c00-d6f36bea8875.png)

Since this is fixed in the latest master, this issue can be closed.
