### ISSUE TITLE
Shortcut only available for userguide in "Help" menu

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3483]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

Please see the attached image, if shortcuts are to be given, it has to be given for all options or for nothing. 

![composer_shortcuts](https://user-images.githubusercontent.com/15624590/31389784-ba9ed3ba-adef-11e7-94bf-b2c21878142c.png)

**Comment by hevayo** [comment]
Not really! shortcuts are required for commonly used functions. Checked with multiple editors and they also have the same.

**Comment by erandidesilva** [comment]
That is the exact thing. If shortcut is given, it has to be given for all. That is what the issue is about.

**Comment by hevayo** [comment]
Checked Idea , VS Code and Atom none of them have a shortcut to welcome page indicating this is not a commonly used scenario. Also that's give us a problem of finding what the shortcut should be ( Please suggest the shortcut if you have anything in mind ) ?

I will be closing this issue for now, please re-open if you think otherwise.
