### ISSUE TITLE
Adding a try catch in source view doesn't auto import

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3614]
![screenshot from 2017-10-12 17-02-23](https://user-images.githubusercontent.com/7681361/31494023-37c3285c-af6f-11e7-8d5c-688d462452ec.png)

**Comment by nadeeshaan** [comment]
This is a limitation in the current autocompletion/ language server. Hence keep this as on hold

**Comment by NatashaWso2** [comment]
With the new syntax change 'error' is in the builtin package so we don't need to automatically import the builtin package. 
![trycatch](https://user-images.githubusercontent.com/13446645/32541416-a47ef382-c495-11e7-9b07-94719660db24.png)

Since this is fixed in the latest master, this issue can be closed
