### ISSUE TITLE
Invalid port number prevents design view from loading / split view related issue

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3636]
*Steps*

1. Create the following program

```
import ballerina.net.http;

function main (string[] args) {
}
@http:configuration {
    host:"localhost",
    port:1235
}
service<http> service1 {
    resource echo1 (http:Request req,http:Response res) {
    }
}
```
2. Now open the split view.
3. From the source section, add a character to the port number. e.g: port:1235a
4. Click close split view button.

**Issue:** The design view keeps on loading, and there is no way to recover other than reloading the entire page.

**Comment by NatashaWso2** [comment]
When the user provides an invalid port number from the split view (i.e. a character to a numeric type variable), the following syntax error would be given and the user cannot close the split view button unless that issue is resolved. 
![syntax-error-int](https://user-images.githubusercontent.com/13446645/33200709-bc632616-d11b-11e7-8847-216807694521.png)

Since this is fixed in the latest master, this issue can be resolved.
