### ISSUE TITLE
[Intermittent] Transform view does not show the design

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3663]
Transform view does not show the design even though the source view has the code.
![25](https://user-images.githubusercontent.com/1845370/31501853-097ac7f6-af89-11e7-8490-f014bbffbf57.PNG)

**Comment by dilinisg** [comment]
Source code for the above issue is as follows. This issue will show up if you un-comment the commented lines. These lines were added from the target of the transform view

```
import ballerina.lang.strings;
import ballerina.lang.system;


function getFirstName (string name) (string) {
    string[] names = strings:split(name," ");
    return names[0];
}

function main (string[] args) {

   // json var2 = { "name":"John", "age":30, "car":null };

   // any var1rr = "eeee";

  //  string var0 = "test";
    
    Person p = {fname: "John Allen", age: 30,city: "London", lname:"Andy", count:5};
    User u = {};

transform {
    
boolean istrue = false;
    
int intVa = 3;
    
string tempVar0 = "";
    
json jtemp = { "name":"John", "age":30, "car":null };

    u.location = strings:toLowerCase(strings:toUpperCase(""));
    u.username =  strings:toUpperCase(getFirstName(p.fname)) + p.lname;
    

   
}
    system:println(u.username );
    system:println(u.location);
    system:println(u.age);
    system:println(u.val);
   
}


struct Person {
    string fname;
    int age;
    string city;
    string lname;
    int count;
}

struct User {
    string username;
    string location;
    int age;
    boolean val;
}
```

**Comment by keizer619** [comment]
This code will cause multiple issues. First there is a problem with JSON declarations in language server, i have created that an issue for that [1]. Even when declarations are commented there was an issue in the language server, which i have fixed in following PR [2], Hence i am closing this issue.
[1] https://github.com/ballerinalang/composer/issues/3731
[2] https://github.com/ballerinalang/composer/pull/3722
