### ISSUE TITLE
[Intermittent] The variables are getting disappeared time to time

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3785]
The variables are getting disappeared time to time from the transform view
![53](https://user-images.githubusercontent.com/1845370/31621364-25f9f880-b2b7-11e7-972f-c7989d936093.png)

**Comment by dilinisg** [comment]
This happens in both source and target.

**Comment by keizer619** [comment]
The cause for this behavior is, drop down selections do not change the code.

If you select a source/target from drop down, it changes UI to map but it doesn't change the transform code block unless you map the selection. After that if you do a code change/action which will render diagram from the code, that will clear unmapped selections. Since you can select them again from the drop down lists and continue to complete the mapping, i am reducing the severity :)

**Comment by keizer619** [comment]
With transformer syntax update in 0.95, this does not happen as Source and Target is attached to transformer signature.
