### ISSUE TITLE
Can add return statement to the main function

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3832]

**Comment by maheeka** [comment]
Adding a return to the main function will change it to a normal function. See screenshot below.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1029806/32851709-abc3e51a-ca2d-11e7-9fed-f40cebaba394.png">

This is the expected behaviour. If the function does not adhere to "function main(string[] args)" signature, it is treated as a normal function.

See thread https://groups.google.com/d/msg/ballerina-dev/P9j33MROQTU/NgVC1-QWBgAJ
