### ISSUE TITLE
Run returns an error for certain file names

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/composer#3963]
1) create file name with spaces 'dakshika me.bal'

2) save and use the run option

ballerina: an internal error occurred

note: this return expected results in ballerina run filename.bal

**Comment by maheeka** [comment]
The original issue no longer exists. Observed the below. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/1029806/32828180-4dbebe46-c9e6-11e7-9b04-8542936d5934.png">

**Comment by pahans** [comment]
To fix this we need to use `java.lang.Runtime.exec(String[] cmdarray)` instead of `java.lang.Runtime.exec(String command)` in the [run command](https://github.com/ballerinalang/composer/blob/4b127679fd7be118bee236f5ed6167c2e31844b6/modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LaunchManager.java#L103)
