### ISSUE TITLE
No values are displayed for the variables inside transform block 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4019]
![17](https://user-images.githubusercontent.com/1845370/31771964-930515b8-b4fb-11e7-9163-9f98e90df074.png)

**Comment by keizer619** [comment]
I have analyzed this issue, actually values inside transform does show in the debugger. In the above sample its breaking after "Person p" struct declaration that's why "p" and "u" struct values are also null. This happens only for struct definitions which as XML declaration attribute declaration. Hence i am closing this and opening issue in the core [1]. 

[1] https://github.com/ballerinalang/ballerina/issues/3716
