### ISSUE TITLE
[WS] Values are not saved in configuration pop up "subprotocol" section

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4255]
Browser: Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)

As shown in the below image, the "Sub Protocol" section is a text box. But just entering values in a comma seperated manner or as " ["xml", "json"]" does not effect as the values are not saved. 

![com_0 94_new_1](https://user-images.githubusercontent.com/15624590/32140533-53a5fa04-bc8a-11e7-8109-386600e4e977.png)

**Comment by NatashaWso2** [comment]
The sub protocol section in the WS configuration is a tagged input field i.e. it is of array type. You can provide multiple values to that particular field. You can enter the values to that field by typing the value and by pressing enter it would add that value to the array. So likewise you can add multiple values to that field since it is of array type.
A screen shot is attached.
![ws](https://user-images.githubusercontent.com/13446645/32140725-145a3f16-bc91-11e7-8278-b8c715360c01.png)

**Comment by erandidesilva** [comment]
Thanks Natasha for the explanation, but will a user know that he has to enter to get the values entered properly? Since there is no tool tip or any information on how to use it, a user will definetly face the problem I have faced. So it's better to provide a tip of usage.
