### ISSUE TITLE
What is the difference between 'SSL Enabled Protocols' and 'SSL protocols' in client connector configs

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4256]
![screenshot from 2017-10-29 09-22-02](https://user-images.githubusercontent.com/7681361/32140539-efb87688-bc8a-11e7-82e6-b66ccf3fab30.png)

**Comment by NatashaWso2** [comment]
Will be populating the placeholders of these input fields in the connector property window from doc annotations in the core when it is available. These doc annotations should explain the proper meanings of each of the input fields. Until this support is available, this issue will be on hold.
This issue is referenced in #4065 , so closing this issue
