### ISSUE TITLE
Error messages are not meaningful in transform

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4432]
Error message that is coming as soon as a transform is added is not meaningful
"type conversion is already exists from other to other"
![14](https://user-images.githubusercontent.com/1845370/32402963-3e8fafb4-c155-11e7-946c-64f45ae1ab36.png)

**Comment by keizer619** [comment]
This is happening when drag and drop a Transformer it will add Dummy source and target which types are Dummy types. At that point no point of placing a primitive type like string or int as transformers main task is for complex types like structs. Since these types are dummy those are identified as 'other'.  Since primitive type casting are already available in the language these errors are given. This could happen even if you change it into string.

To avoid those we are adding a name for transformer in drag and drop [1]. Hence i am closing this issue

https://github.com/ballerinalang/composer/commit/4b6f50f181378448eff9ccbb0d46a00f70f0f667#diff-87065534c63834ef61208e7cc0d6f1b1R233
