### ISSUE TITLE
Transform is unusable-gives syntax errors every time a change is done

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4436]
Transform is unusable-gives syntax errors every time a change (mapping) is done

![15](https://user-images.githubusercontent.com/1845370/32403261-6cd5602a-c15b-11e7-9ff6-2565239d9dc9.png)

**Comment by nadeeshaan** [comment]
This is since there is a syntax error in the transformer signature. publicTransform. This issue has been fixed in the latest head. 
Note: Also, when the user is typing, the intermediate source is an incomplete one. If the source is incomplete we show the errors while typing, with a latency. 

Hence closing the issue
