### ISSUE TITLE
[Throw] Default code gen results in an error

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4466]
As shown in the attached image, the default generated code results in an error. 

![com_0 95_new_4](https://user-images.githubusercontent.com/15624590/32413730-d0824d4e-c23d-11e7-89df-0023832b1490.png)

**Comment by nadeeshaan** [comment]
When dragging and dropping a statement, if it refers a variable, we generate a temp variable. The followed design decision was, that the user will need to change the variable name accordingly. In order to avoid the user being misguided, we are showing the semantic errors and the user is driven to change the semantic error.
Hence closing
