### ISSUE TITLE
The link to connector to action is not available for connectors

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4507]
The link to connector to action is not available for connectors. So its not consistent with other connectors.
![60](https://user-images.githubusercontent.com/1845370/32428660-edcc4d82-c2ec-11e7-8495-96d47e7e76e6.png)

![61](https://user-images.githubusercontent.com/1845370/32428683-0ab36f5c-c2ed-11e7-99be-df1a85f710a8.png)

**Comment by NatashaWso2** [comment]
The link is drawn only for services and its resources and not for connectors and its actions. This is because the services and connectors are not the same and they have different designs. So according to the concepts of services and connectors we only show the link between the services and its resources and not the connectors with its actions. So this issue can be closed
