### ISSUE TITLE
Auto suggest sqlTypes in composer

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4631]
**Description:**
Currently, composer doesn't give an error if you add an incorrect SQL type. 

e.g : `sql:Parameter para1 = {sqlType:"varcharAAAAAAA", value:token, direction:0};`

Is it possible to validate this?

**Affected Product Version:**
0.95

**Comment by hevayo** [comment]
Composer will not be able to special case for sqlTypes and the fix is to change the sqlType in to an enum. Once the enum is implemented we can do auto suggest for enum attributes. 

Please see https://github.com/ballerinalang/ballerina/issues/4100 for the enum fix. 

Completion task was captured in https://github.com/ballerinalang/composer/issues/4696
