### ISSUE TITLE
[Design view] Can typeof and lengthof be supported as drop ins?

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4678]
$subject please.

**Comment by NatashaWso2** [comment]
typeOf and lengthOf are operators. In the tool palette we have only provided **constructs** which can be dragged and dropped to the canvas. So having typeOf and lengthOf operators in the tool palette will be inconsistent. 
Since operators are needed for the transformer, we have provided these operators in the tool palette of the transformer construct. 
![operators](https://user-images.githubusercontent.com/13446645/33063886-e3b53a8c-cec9-11e7-8c1c-f894bbe59a4b.png)

And if we include typeOf and lengthOf operators in the composer tool palette, we would have to  show all  other unary, binary and ternary operators as well which will not be significant to the user. Hence this issue can be closed.

**Comment by erandidesilva** [comment]
@NatashaWso2 

typeof and lengthof has a usage which goes beyond being only used inside the transformer construct. These are typically used in statements that does not need any transformer intervention

e.g. finding length of an array. 

Hence the argument given above is not acceptable. Although other operators might be insignificant to the user, these special ones which has a broader usage should be addressed separately.

**Comment by hevayo** [comment]
Currently most atomic element that can be DnD are statement and operators generally finer element than that. So to allow operator DnD we should implement a feature which will allow to DnD on top of statements.

On a general note the direction is only to allow DnD to more high level elements and we will get rid of even statement DnD (ie assignment, variabledef ) due lack of usability. 

Just to note operators completely make sense in transformer since you map to each operator. 

Closing the issue given above.
