### ISSUE TITLE
[Design view] if-else if construct

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4682]
Currently only if-else if available. Can we provide $subject as well?

**Comment by NatashaWso2** [comment]
The user can add an 'else-if' block by clicking on the '+' button provided inside the 'if' block as below:
![else-if-block](https://user-images.githubusercontent.com/13446645/33070301-9882b0b2-cedd-11e7-859c-bdc3b98cb315.png)

Since this is functionality is provided in the latest master, this issue can be closed.
