### ISSUE TITLE
Rename "Remove folder" option as "Remove folder from Composer"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#843]
Built on:b9cf76edd0661dec50e07839d6eab0092cb89c10
Currently the remove folder and the delete folder options look the same to a user at first glance. Please rename "Remove folder" option to "Remove folder from Composer" so that it's distinguishable at first glance.

**Comment by nadeeshaan** [comment]
@erandidesilva, basically what you are comparing is two different design perspectives. In the ballerina composer (which is an editor instead of an IDE). In an editor like sublime, if you consider the editor approach in a such we have the both options to delete the folder (Which intuitive for not being able to get it back) and remove from project(Similar to composer's remove from composer).
I think your suggestion is not an issue, instead another design perspective. Since from the creating a file of the composer, we have followed the former approach (Current approach) and we'll be stick to this due to the design decisions. Hence closing the issue
