### ISSUE TITLE
Debug points are shown in wrong lines

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#861]
Please see the attached images. The line numbers of the added debug points are wrong.
![composer_bug_debuglineno_1](https://cloud.githubusercontent.com/assets/15624590/23092213/f43c7dd2-f5eb-11e6-94dd-8ba12b01f318.png)
![composer_bug_debugpointslineno_2](https://cloud.githubusercontent.com/assets/15624590/23092212/f43b351c-f5eb-11e6-9b22-d314170e8489.png)

**Comment by hevayo** [comment]
This is the result of editor not reflecting new lines and white spaces in a bal file. This can be asserted by saving the above files from the editor and then try to mark the debug points again, which will mark correctly there after. 

The fix is bit complicated where we need capture the white spaces in the bal model and serialize them accordingly in the editor.

**Comment by hevayo** [comment]
We have done a partial fix #1074 , in order to properly fix this you need to fix the original issues which is reported under #1075
